on: [push]

name: CI

jobs:
  build_and_test:
    name: bread-CI
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: release build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: test
        uses: actions-rs/cargo@v1
        with:
          command: test
